OpenSim: OpenSim::Property_Deprecated Class Reference
OpenSim::Property_Deprecated Class Reference abstract
#include <Property_Deprecated.h>
Public Types
enum PropertyType {
None =0, Bool, Int, Dbl,
Str, Obj, ObjPtr, BoolArray,
IntArray, DblArray, StrArray, ObjArray,
DblVec, DblVec3, Transform
}
Enumeration of recognized types.
Public Member Functions
Property_Deprecated ()
Property_Deprecated (PropertyType aType, const std::string &aName)
Property_Deprecated (const Property_Deprecated &aProperty)
virtual PropertyType getPropertyType () const
Return the enum value corresponding to the concrete property.
virtual bool isArrayProperty () const
Return true if this is an array property.
void setMatchName (bool aMatchName)
By default deprecated PropertyObj properties will ignore the name associated with the read-in object.
bool getMatchName () const
Return the value of the matchName flag for this (deprecated) property.
bool isEqualTo (const AbstractProperty &other) const override
The base class equals() method will have already done a lot of checking prior to calling this method, including verifying that both values are non-default and that the value lists are the same size; the concrete property need only compare the values.
Property_Deprecated * clone () const override=0
Return a new instance of this concrete property object, containing new copies of this property's values.
virtual void readFromXMLElement (SimTK::Xml::Element &propertyElement, int versionNumber) override
Read in a new value for this property from the XML element propertyElement.
virtual void writeToXMLElement (SimTK::Xml::Element &propertyElement) const override
Output a serialized representation of this property by writing its value to the given XML property element.
virtual int getNumValues () const override
How may values are currently stored in this property? If this is an object property you can use this with getValueAsObject() to iterate over the contained objects.
virtual void clearValues () override
If the concrete property allows it, clear the value list.
virtual bool isUnnamedProperty () const override
An unnamed property is a one-object property whose name was given as null or as the contained object's type tag.
virtual bool isObjectProperty () const override
Return true if this is an "object property", meaning that its values are all concrete objects of types that ultimately derive from the OpenSim serializable base class Object.
virtual bool isAcceptableObjectTag (const std::string &objectTypeTag) const override
Return true if the given string is the XML tag name for one of the Object-derived types that is allowed by this property.
virtual const Object & getValueAsObject (int index=-1) const override
For an object property, the values can be obtained as references to the abstract base class Object from which all the objects derive.
virtual Object & updValueAsObject (int index=-1) override
Get writable access to an existing object value.
virtual void setValueAsObject (const Object &obj, int index=-1) override
Set the indicated value element to a new copy of the supplied object.
void setNull ()
Property_Deprecated & operator= (const Property_Deprecated &aProperty)
virtual bool operator== (const Property_Deprecated &aProperty) const
virtual bool operator< (const Property_Deprecated &aProperty) const
void setType (PropertyType aType)
PropertyType getType () const
virtual std::string getTypeName () const override=0
This returns a string representation of this property's value type which will be the same as T::getClassName() for Object-derived types T, and some reasonably nice name for simple types, including at least "bool", "int", "double", "string", "Vec3", "Vector", and "Transform".
virtual std::string toString () const override=0
For relatively simple types, return the current value of this property in a string suitable for displaying to a user in the GUI.
virtual void setValue (bool aValue)
virtual bool & getValueBool ()
virtual const bool & getValueBool () const
virtual void setValue (int aValue)
virtual int & getValueInt ()
virtual const int & getValueInt () const
virtual void setValue (double aValue)
virtual double & getValueDbl ()
virtual const double & getValueDbl () const
virtual void setValue (const std::string &aValue)
virtual std::string & getValueStr ()
virtual const std::string & getValueStr () const
virtual void setValue (int aSize, const bool aArray[])
virtual void setValue (const Array< bool > &aArray)
virtual Array< bool > & getValueBoolArray ()
virtual const Array< bool > & getValueBoolArray () const
virtual void setValue (int aSize, const int aArray[])
virtual void setValue (const Array< int > &aArray)
virtual Array< int > & getValueIntArray ()
virtual const Array< int > & getValueIntArray () const
virtual void setValue (int aSize, const double aArray[])
virtual void setValue (const Array< double > &aArray)
virtual Array< double > & getValueDblArray ()
virtual const Array< double > & getValueDblArray () const
virtual void setValue (int aSize, const std::string aArray[])
virtual void setValue (const Array< std::string > &aArray)
virtual Array< std::string > & getValueStrArray ()
virtual const Array
< std::string > & getValueStrArray () const
virtual bool isValidObject (const Object *aValue) const
virtual Object & getValueObj ()
virtual const Object & getValueObj () const
virtual void setValue (Object *aValue)
virtual Object * getValueObjPtr ()
virtual Object * getValueObjPtr (int index)
virtual void appendValue (Object *obj)
virtual void clearObjArray ()
virtual int getArraySize () const
template<class T >
T & getValue ()
template<class T >
const T & getValue () const
template<class T >
Array< T > & getValueArray ()
template<class T >
const Array< T > & getValueArray () const
template<>
bool & getValue ()
template<>
const bool & getValue () const
template<>
int & getValue ()
template<>
const int & getValue () const
template<>
double & getValue ()
template<>
const double & getValue () const
template<>
std::string & getValue ()
template<>
const std::string & getValue () const
template<>
Array< bool > & getValue ()
template<>
const Array< bool > & getValue () const
template<>
Array< int > & getValue ()
template<>
const Array< int > & getValue () const
template<>
Array< double > & getValue ()
template<>
const Array< double > & getValue () const
template<>
Array< std::string > & getValue ()
template<>
const Array< std::string > & getValue () const
template<>
Array< bool > & getValueArray ()
template<>
const Array< bool > & getValueArray () const
template<>
Array< int > & getValueArray ()
template<>
const Array< int > & getValueArray () const
template<>
Array< double > & getValueArray ()
template<>
const Array< double > & getValueArray () const
template<>
Array< std::string > & getValueArray ()
template<>
const Array< std::string > & getValueArray () const
Public Member Functions inherited from OpenSim::AbstractProperty
void setAllowableListSize (int aMin, int aMax)
Require that the number of values n in the value list of this property be in the range aMin <= n <= aMax.
void setAllowableListSize (int aNum)
Require that the number of values n in the value list of this property be exactly n=aNum values.
virtual ~AbstractProperty ()
Return all heap space used by this property.
bool equals (const AbstractProperty &other) const
Compare this property with another one; this is primarily used for testing.
bool isSamePropertyClass (const AbstractProperty &other) const
Return true if the other property is an object of exactly the same concrete class as this one.
bool operator== (const AbstractProperty &other) const
See the equals() method for the meaning of this operator.
void setAllPropertiesUseDefault (bool shouldUseDefault)
This method sets the "use default" flag for this property and the properties of any objects it contains to the given value.
void readFromXMLParentElement (SimTK::Xml::Element &parent, int versionNumber)
Given an XML parent element expected to contain a value for this property as an immediate child element, find that property element and set the property value from it.
void writeToXMLParentElement (SimTK::Xml::Element &parent)
Given an XML parent element, append a single child element representing the serialized form of this property.
void setName (const std::string &name)
Set the property name.
void setComment (const std::string &aComment)
Set a user-friendly comment to be associated with property.
void setValueIsDefault (bool isDefault)
Set flag indicating whether the value of this property was simply taken from a default object and thus should not be written out when serializing.
const std::string & getName () const
Get the property name.
const std::string & getComment () const
Get the comment associated with this property.
bool getValueIsDefault () const
Get the flag indicating whether the current value is just the default value for this property (in which case it doesn't need to be written out).
int getMinListSize () const
Get the minimum number of values allowed in this property's value list.
int getMaxListSize () const
Get the maximum number of values allowed in this property's value list.
bool isOptionalProperty () const
This is an "optional" property if its value list can contain at most one value.
bool isListProperty () const
This is a "list" property if its value list can contain more than one value.
bool isOneValueProperty () const
This is a "one-value" property if its value list must always contain exactly one value.
bool isOneObjectProperty () const
This is a "one-object" property if it is a "one-value" property and it contains an Object-derived value.
int size () const
Return the number of values currently in this property's value list.
bool empty () const
Return true if this property's value list is currently empty.
void clear ()
Empty the value list for this property; fails if zero is not an allowable size for this property.
template<class T >
const T & getValue (int index=-1) const
Return one of the values in this property as type T; this works only if the underlying concrete property stores type T and if the indexed element is present, otherwise throws an exception.
template<class T >
T & updValue (int index=-1)
Return a writable reference to one of the values in this property as type T; this works only if the underlying concrete property is actually of type T and the indexed element is present.
template<class T >
int appendValue (const T &value)
Append a new value of type T to the end of the list of values currently contained in this property.
Friends
std::ostream & operator<< (std::ostream &aOut, const Property_Deprecated &aProperty)
Additional Inherited Members
Protected Member Functions inherited from OpenSim::AbstractProperty
AbstractProperty ()
AbstractProperty (const std::string &name, const std::string &comment)
Member Enumeration Documentation
enum OpenSim::Property_Deprecated::PropertyType
Enumeration of recognized types.
Enumerator
None
Bool
Int
Dbl
Str
Obj
ObjPtr
BoolArray
IntArray
DblArray
StrArray
ObjArray
DblVec
DblVec3
Transform
Constructor & Destructor Documentation
OpenSim::Property_Deprecated::Property_Deprecated ()
OpenSim::Property_Deprecated::Property_Deprecated (PropertyType aType, const std::string & aName)
OpenSim::Property_Deprecated::Property_Deprecated (const Property_Deprecated & aProperty)
Member Function Documentation
virtual void OpenSim::Property_Deprecated::appendValue (Object * obj) inline virtual
Reimplemented in OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, and OpenSim::PropertyObjArray< Control >.
virtual void OpenSim::Property_Deprecated::clearObjArray () inline virtual
Reimplemented in OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, and OpenSim::PropertyObjArray< Control >.
virtual void OpenSim::Property_Deprecated::clearValues () inline override virtual
If the concrete property allows it, clear the value list.
Implements OpenSim::AbstractProperty.
Reimplemented in OpenSim::PropertyDblArray, OpenSim::PropertyStrArray, OpenSim::PropertyIntArray, and OpenSim::PropertyBoolArray.
Property_Deprecated* OpenSim::Property_Deprecated::clone () const override pure virtual
Return a new instance of this concrete property object, containing new copies of this property's values.
The new property object is allocated on the heap and it is up to the caller to delete it when done.
Implements OpenSim::AbstractProperty.
Implemented in OpenSim::PropertyDblVec_< M >, OpenSim::PropertyDblVec_< 2 >, OpenSim::PropertyDblVec_< 3 >, OpenSim::PropertyDblArray, OpenSim::PropertyIntArray, OpenSim::PropertyObjPtr< T >, OpenSim::PropertyStrArray, OpenSim::PropertyObjPtr< OpenSim::OpenSim::Function >, OpenSim::PropertyObjPtr< OpenSim::Joint >, OpenSim::PropertyObjPtr< OpenSim::Function >, OpenSim::PropertyBoolArray, OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, OpenSim::PropertyObjArray< Control >, OpenSim::PropertyObj, OpenSim::PropertyTransform, OpenSim::PropertyBool, OpenSim::PropertyDbl, OpenSim::PropertyInt, and OpenSim::PropertyStr.
virtual int OpenSim::Property_Deprecated::getArraySize () const inline virtual
Reimplemented in OpenSim::PropertyDblVec_< M >, OpenSim::PropertyDblVec_< 2 >, OpenSim::PropertyDblVec_< 3 >, OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, OpenSim::PropertyObjArray< Control >, OpenSim::PropertyDblArray, OpenSim::PropertyStrArray, OpenSim::PropertyIntArray, and OpenSim::PropertyBoolArray.
bool OpenSim::Property_Deprecated::getMatchName () const inline
Return the value of the matchName flag for this (deprecated) property.
virtual int OpenSim::Property_Deprecated::getNumValues () const inline override virtual
How may values are currently stored in this property? If this is an object property you can use this with getValueAsObject() to iterate over the contained objects.
Implements OpenSim::AbstractProperty.
Reimplemented in OpenSim::PropertyDblVec_< M >, OpenSim::PropertyDblVec_< 2 >, OpenSim::PropertyDblVec_< 3 >, OpenSim::PropertyObjPtr< T >, OpenSim::PropertyObjPtr< OpenSim::OpenSim::Function >, OpenSim::PropertyObjPtr< OpenSim::Joint >, OpenSim::PropertyObjPtr< OpenSim::Function >, OpenSim::PropertyDblArray, OpenSim::PropertyIntArray, OpenSim::PropertyStrArray, OpenSim::PropertyBoolArray, OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, and OpenSim::PropertyObjArray< Control >.
Referenced by OpenSim::AbstractProperty::appendValue().
virtual PropertyType OpenSim::Property_Deprecated::getPropertyType () const inline virtual
Return the enum value corresponding to the concrete property.
PropertyType OpenSim::Property_Deprecated::getType () const
virtual std::string OpenSim::Property_Deprecated::getTypeName () const override pure virtual
This returns a string representation of this property's value type which will be the same as T::getClassName() for Object-derived types T, and some reasonably nice name for simple types, including at least "bool", "int", "double", "string", "Vec3", "Vector", and "Transform".
Implements OpenSim::AbstractProperty.
Implemented in OpenSim::PropertyObjPtr< T >, OpenSim::PropertyObjPtr< OpenSim::OpenSim::Function >, OpenSim::PropertyObjPtr< OpenSim::Joint >, OpenSim::PropertyObjPtr< OpenSim::Function >, OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, OpenSim::PropertyObjArray< Control >, OpenSim::PropertyDblVec_< M >, OpenSim::PropertyDblVec_< 2 >, OpenSim::PropertyDblVec_< 3 >, OpenSim::PropertyObj, OpenSim::PropertyDblArray, OpenSim::PropertyIntArray, OpenSim::PropertyStrArray, OpenSim::PropertyBoolArray, OpenSim::PropertyTransform, OpenSim::PropertyStr, OpenSim::PropertyDbl, OpenSim::PropertyBool, and OpenSim::PropertyInt.
template<class T > T& OpenSim::Property_Deprecated::getValue ()
Referenced by OpenSim::AbstractProperty::getValue(), and OpenSim::AbstractProperty::updValue().
template<class T > const T& OpenSim::Property_Deprecated::getValue () const
template<> bool& OpenSim::Property_Deprecated::getValue () inline
References getValueBool().
template<> const bool& OpenSim::Property_Deprecated::getValue () const inline
References getValueBool().
template<> int& OpenSim::Property_Deprecated::getValue () inline
References getValueInt().
template<> const int& OpenSim::Property_Deprecated::getValue () const inline
References getValueInt().
template<> double& OpenSim::Property_Deprecated::getValue () inline
References getValueDbl().
template<> const double& OpenSim::Property_Deprecated::getValue () const inline
References getValueDbl().
template<> std::string& OpenSim::Property_Deprecated::getValue () inline
References getValueStr().
template<> const std::string& OpenSim::Property_Deprecated::getValue () const inline
References getValueStr().
template<> Array<bool>& OpenSim::Property_Deprecated::getValue () inline
References getValueBoolArray().
template<> const Array<bool>& OpenSim::Property_Deprecated::getValue () const inline
References getValueBoolArray().
template<> Array<int>& OpenSim::Property_Deprecated::getValue () inline
References getValueIntArray().
template<> const Array<int>& OpenSim::Property_Deprecated::getValue () const inline
References getValueIntArray().
template<> Array<double>& OpenSim::Property_Deprecated::getValue () inline
References getValueDblArray().
template<> const Array<double>& OpenSim::Property_Deprecated::getValue () const inline
References getValueDblArray().
template<> Array<std::string>& OpenSim::Property_Deprecated::getValue () inline
References getValueStrArray().
template<> const Array<std::string>& OpenSim::Property_Deprecated::getValue () const inline
References getValueStrArray().
template<class T > Array<T>& OpenSim::Property_Deprecated::getValueArray ()
Referenced by OpenSim::AbstractProperty::appendValue(), OpenSim::AbstractProperty::getValue(), and OpenSim::AbstractProperty::updValue().
template<class T > const Array<T>& OpenSim::Property_Deprecated::getValueArray () const
template<> Array<bool>& OpenSim::Property_Deprecated::getValueArray () inline
References getValueBoolArray().
template<> const Array<bool>& OpenSim::Property_Deprecated::getValueArray () const inline
References getValueBoolArray().
template<> Array<int>& OpenSim::Property_Deprecated::getValueArray () inline
References getValueIntArray().
template<> const Array<int>& OpenSim::Property_Deprecated::getValueArray () const inline
References getValueIntArray().
template<> Array<double>& OpenSim::Property_Deprecated::getValueArray () inline
References getValueDblArray().
template<> const Array<double>& OpenSim::Property_Deprecated::getValueArray () const inline
References getValueDblArray().
template<> Array<std::string>& OpenSim::Property_Deprecated::getValueArray () inline
References getValueStrArray().
template<> const Array<std::string>& OpenSim::Property_Deprecated::getValueArray () const inline
References getValueStrArray().
virtual const Object& OpenSim::Property_Deprecated::getValueAsObject (int index = -1) const inline override virtual
For an object property, the values can be obtained as references to the abstract base class Object from which all the objects derive.
If the property can hold a list of values you must provide an index to select the value, otherwise it is optional but if supplied must be 0. This will throw an exception if this is not an object property, that is, if it is a simple property, because its values can't be represented as an Object in that case.
Parameters
[in] index If supplied must be 0 <= index < getNumValues().
Returns
const reference to the value as an Object
See Also
updValueAsObject(), getValue<T>()
Implements OpenSim::AbstractProperty.
Reimplemented in OpenSim::PropertyObjPtr< T >, OpenSim::PropertyObjPtr< OpenSim::OpenSim::Function >, OpenSim::PropertyObjPtr< OpenSim::Joint >, OpenSim::PropertyObjPtr< OpenSim::Function >, OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, OpenSim::PropertyObjArray< Control >, and OpenSim::PropertyObj.
virtual bool& OpenSim::Property_Deprecated::getValueBool () inline virtual
Reimplemented in OpenSim::PropertyBool.
Referenced by getValue().
virtual const bool& OpenSim::Property_Deprecated::getValueBool () const inline virtual
Reimplemented in OpenSim::PropertyBool.
virtual Array<bool>& OpenSim::Property_Deprecated::getValueBoolArray () inline virtual
Reimplemented in OpenSim::PropertyBoolArray.
Referenced by getValue(), and getValueArray().
virtual const Array<bool>& OpenSim::Property_Deprecated::getValueBoolArray () const inline virtual
Reimplemented in OpenSim::PropertyBoolArray.
virtual double& OpenSim::Property_Deprecated::getValueDbl () inline virtual
Reimplemented in OpenSim::PropertyDbl.
Referenced by getValue().
virtual const double& OpenSim::Property_Deprecated::getValueDbl () const inline virtual
Reimplemented in OpenSim::PropertyDbl.
virtual Array<double>& OpenSim::Property_Deprecated::getValueDblArray () inline virtual
Reimplemented in OpenSim::PropertyDblVec_< M >, OpenSim::PropertyDblVec_< 2 >, OpenSim::PropertyDblVec_< 3 >, and OpenSim::PropertyDblArray.
Referenced by getValue(), and getValueArray().
virtual const Array<double>& OpenSim::Property_Deprecated::getValueDblArray () const inline virtual
Reimplemented in OpenSim::PropertyDblVec_< M >, OpenSim::PropertyDblVec_< 2 >, OpenSim::PropertyDblVec_< 3 >, and OpenSim::PropertyDblArray.
virtual int& OpenSim::Property_Deprecated::getValueInt () inline virtual
Reimplemented in OpenSim::PropertyInt.
Referenced by getValue().
virtual const int& OpenSim::Property_Deprecated::getValueInt () const inline virtual
Reimplemented in OpenSim::PropertyInt.
virtual Array<int>& OpenSim::Property_Deprecated::getValueIntArray () inline virtual
Reimplemented in OpenSim::PropertyIntArray.
Referenced by getValue(), and getValueArray().
virtual const Array<int>& OpenSim::Property_Deprecated::getValueIntArray () const inline virtual
Reimplemented in OpenSim::PropertyIntArray.
virtual Object& OpenSim::Property_Deprecated::getValueObj () inline virtual
Reimplemented in OpenSim::PropertyObj.
virtual const Object& OpenSim::Property_Deprecated::getValueObj () const inline virtual
Reimplemented in OpenSim::PropertyObj.
virtual Object* OpenSim::Property_Deprecated::getValueObjPtr () inline virtual
Reimplemented in OpenSim::PropertyObjPtr< T >, OpenSim::PropertyObjPtr< OpenSim::OpenSim::Function >, OpenSim::PropertyObjPtr< OpenSim::Joint >, and OpenSim::PropertyObjPtr< OpenSim::Function >.
Referenced by OpenSim::PropertyObjArray< Control >::getValueAsObject(), and OpenSim::PropertyObjArray< Control >::updValueAsObject().
virtual Object* OpenSim::Property_Deprecated::getValueObjPtr (int index) inline virtual
Reimplemented in OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, and OpenSim::PropertyObjArray< Control >.
virtual std::string& OpenSim::Property_Deprecated::getValueStr () inline virtual
Reimplemented in OpenSim::PropertyStr.
Referenced by getValue().
virtual const std::string& OpenSim::Property_Deprecated::getValueStr () const inline virtual
Reimplemented in OpenSim::PropertyStr.
virtual Array<std::string>& OpenSim::Property_Deprecated::getValueStrArray () inline virtual
Reimplemented in OpenSim::PropertyStrArray.
Referenced by getValue(), and getValueArray().
virtual const Array<std::string>& OpenSim::Property_Deprecated::getValueStrArray () const inline virtual
Reimplemented in OpenSim::PropertyStrArray.
virtual bool OpenSim::Property_Deprecated::isAcceptableObjectTag (const std::string & objectTypeTag) const inline override virtual
Return true if the given string is the XML tag name for one of the Object-derived types that is allowed by this property.
If so, we expect that an element with that tag could be deserialized into a value element of this property. This always returns false for a simple property.
Implements OpenSim::AbstractProperty.
Reimplemented in OpenSim::PropertyObjPtr< T >, OpenSim::PropertyObjPtr< OpenSim::OpenSim::Function >, OpenSim::PropertyObjPtr< OpenSim::Joint >, OpenSim::PropertyObjPtr< OpenSim::Function >, OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, OpenSim::PropertyObjArray< Control >, and OpenSim::PropertyObj.
virtual bool OpenSim::Property_Deprecated::isArrayProperty () const inline virtual
Return true if this is an array property.
Reimplemented in OpenSim::PropertyDblVec_< M >, OpenSim::PropertyDblVec_< 2 >, OpenSim::PropertyDblVec_< 3 >, OpenSim::PropertyDblArray, OpenSim::PropertyIntArray, OpenSim::PropertyStrArray, OpenSim::PropertyBoolArray, OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, and OpenSim::PropertyObjArray< Control >.
Referenced by OpenSim::AbstractProperty::appendValue(), OpenSim::AbstractProperty::getValue(), and OpenSim::AbstractProperty::updValue().
bool OpenSim::Property_Deprecated::isEqualTo (const AbstractProperty & other) const inline override virtual
The base class equals() method will have already done a lot of checking prior to calling this method, including verifying that both values are non-default and that the value lists are the same size; the concrete property need only compare the values.
Implements OpenSim::AbstractProperty.
virtual bool OpenSim::Property_Deprecated::isObjectProperty () const inline override virtual
Return true if this is an "object property", meaning that its values are all concrete objects of types that ultimately derive from the OpenSim serializable base class Object.
If this returns true then it is safe to call getValueAsObject(). Otherwise this property contains only simple types like "int" or "std::string", and you'll need to know the actual type in order to access the values.
Implements OpenSim::AbstractProperty.
Reimplemented in OpenSim::PropertyObjPtr< T >, OpenSim::PropertyObjPtr< OpenSim::OpenSim::Function >, OpenSim::PropertyObjPtr< OpenSim::Joint >, OpenSim::PropertyObjPtr< OpenSim::Function >, OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, OpenSim::PropertyObjArray< Control >, and OpenSim::PropertyObj.
virtual bool OpenSim::Property_Deprecated::isUnnamedProperty () const inline override virtual
An unnamed property is a one-object property whose name was given as null or as the contained object's type tag.
In that case getName() will return the object type tag, and the XML representation will just be the object, with name attribute ignored if there is one.
Implements OpenSim::AbstractProperty.
virtual bool OpenSim::Property_Deprecated::isValidObject (const Object * aValue) const inline virtual
Reimplemented in OpenSim::PropertyObjPtr< T >, OpenSim::PropertyObjPtr< OpenSim::OpenSim::Function >, OpenSim::PropertyObjPtr< OpenSim::Joint >, OpenSim::PropertyObjPtr< OpenSim::Function >, OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, OpenSim::PropertyObjArray< Control >, and OpenSim::PropertyObj.
virtual bool OpenSim::Property_Deprecated::operator< (const Property_Deprecated & aProperty) const virtual
Property_Deprecated& OpenSim::Property_Deprecated::operator= (const Property_Deprecated & aProperty)
Referenced by OpenSim::PropertyObjArray< Control >::operator=(), and OpenSim::PropertyObjPtr< OpenSim::Function >::operator=().
virtual bool OpenSim::Property_Deprecated::operator== (const Property_Deprecated & aProperty) const virtual
Reimplemented in OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, OpenSim::PropertyObjArray< Control >, OpenSim::PropertyObjPtr< T >, OpenSim::PropertyObjPtr< OpenSim::OpenSim::Function >, OpenSim::PropertyObjPtr< OpenSim::Joint >, and OpenSim::PropertyObjPtr< OpenSim::Function >.
Referenced by OpenSim::PropertyObjPtr< OpenSim::Function >::operator==(), and OpenSim::PropertyObjArray< Control >::operator==().
virtual void OpenSim::Property_Deprecated::readFromXMLElement (SimTK::Xml::Element & propertyElement, int versionNumber) inline override virtual
Read in a new value for this property from the XML element propertyElement.
The element is expected to have the form
<propertyName> value(s) </propertyName>
where the values may be simple (like int or double) or may be objects contained in child elements for which the object type name serves as the element tag. Note that although the XML file may contain an abbreviated representation for one-object properties, it will have been canonicalized into the above form for the purpose of reading, so concrete properties may assume the above form always.
The format for the property value (and any of its contained objects) is assumed to be the one that was in use when the given ".osim" file version number was current; if necessary the in-memory version will be updated to the now-current format.
If this is an object property, the contained objects will be asked recursively to read themselves in from the same document. However, any object that has the "file" attribute will read in its contents from that file rather than from the supplied XML document, and the version number will be taken from that file rather than the argument supplied here.
Implements OpenSim::AbstractProperty.
void OpenSim::Property_Deprecated::setMatchName (bool aMatchName) inline
By default deprecated PropertyObj properties will ignore the name associated with the read-in object.
This forces the name to match one specified for the property. Note that this is handled differently in the new Property system.
void OpenSim::Property_Deprecated::setNull ()
void OpenSim::Property_Deprecated::setType (PropertyType aType)
virtual void OpenSim::Property_Deprecated::setValue (bool aValue) inline virtual
Reimplemented in OpenSim::PropertyBool.
virtual void OpenSim::Property_Deprecated::setValue (int aValue) inline virtual
Reimplemented in OpenSim::PropertyInt.
virtual void OpenSim::Property_Deprecated::setValue (double aValue) inline virtual
Reimplemented in OpenSim::PropertyDbl.
virtual void OpenSim::Property_Deprecated::setValue (const std::string & aValue) inline virtual
Reimplemented in OpenSim::PropertyStr.
virtual void OpenSim::Property_Deprecated::setValue (int aSize, const bool aArray[]) inline virtual
Reimplemented in OpenSim::PropertyBoolArray.
virtual void OpenSim::Property_Deprecated::setValue (const Array< bool > & aArray) inline virtual
Reimplemented in OpenSim::PropertyBoolArray.
virtual void OpenSim::Property_Deprecated::setValue (int aSize, const int aArray[]) inline virtual
Reimplemented in OpenSim::PropertyIntArray.
virtual void OpenSim::Property_Deprecated::setValue (const Array< int > & aArray) inline virtual
Reimplemented in OpenSim::PropertyIntArray.
virtual void OpenSim::Property_Deprecated::setValue (int aSize, const double aArray[]) inline virtual
Reimplemented in OpenSim::PropertyDblVec_< M >, OpenSim::PropertyDblVec_< 2 >, OpenSim::PropertyDblVec_< 3 >, OpenSim::PropertyDblArray, and OpenSim::PropertyTransform.
virtual void OpenSim::Property_Deprecated::setValue (const Array< double > & aArray) inline virtual
Reimplemented in OpenSim::PropertyDblVec_< M >, OpenSim::PropertyDblVec_< 2 >, OpenSim::PropertyDblVec_< 3 >, OpenSim::PropertyDblArray, and OpenSim::PropertyTransform.
virtual void OpenSim::Property_Deprecated::setValue (int aSize, const std::string aArray[]) inline virtual
Reimplemented in OpenSim::PropertyStrArray.
virtual void OpenSim::Property_Deprecated::setValue (const Array< std::string > & aArray) inline virtual
Reimplemented in OpenSim::PropertyStrArray.
virtual void OpenSim::Property_Deprecated::setValue (Object * aValue) inline virtual
Reimplemented in OpenSim::PropertyObjPtr< T >, OpenSim::PropertyObjPtr< OpenSim::OpenSim::Function >, OpenSim::PropertyObjPtr< OpenSim::Joint >, and OpenSim::PropertyObjPtr< OpenSim::Function >.
virtual void OpenSim::Property_Deprecated::setValueAsObject (const Object & obj, int index = -1) inline override virtual
Set the indicated value element to a new copy of the supplied object.
If you already have a heap-allocated object you're willing to give up and want to avoid the extra copy, use adoptValueObject().
Implements OpenSim::AbstractProperty.
Reimplemented in OpenSim::PropertyObjPtr< T >, OpenSim::PropertyObjPtr< OpenSim::OpenSim::Function >, OpenSim::PropertyObjPtr< OpenSim::Joint >, OpenSim::PropertyObjPtr< OpenSim::Function >, OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, OpenSim::PropertyObjArray< Control >, and OpenSim::PropertyObj.
virtual std::string OpenSim::Property_Deprecated::toString () const override pure virtual
For relatively simple types, return the current value of this property in a string suitable for displaying to a user in the GUI.
Objects just return something like "(Object)".
Implements OpenSim::AbstractProperty.
Implemented in OpenSim::PropertyDblVec_< M >, OpenSim::PropertyObjPtr< T >, OpenSim::PropertyDblVec_< 2 >, OpenSim::PropertyDblVec_< 3 >, OpenSim::PropertyObjPtr< OpenSim::OpenSim::Function >, OpenSim::PropertyObjPtr< OpenSim::Joint >, OpenSim::PropertyObjPtr< OpenSim::Function >, OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, OpenSim::PropertyObjArray< Control >, OpenSim::PropertyDblArray, OpenSim::PropertyObj, OpenSim::PropertyStrArray, OpenSim::PropertyIntArray, OpenSim::PropertyBoolArray, OpenSim::PropertyTransform, OpenSim::PropertyStr, OpenSim::PropertyDbl, OpenSim::PropertyBool, and OpenSim::PropertyInt.
virtual Object& OpenSim::Property_Deprecated::updValueAsObject (int index = -1) inline override virtual
Get writable access to an existing object value.
Note that you can't use this to install a different concrete object; see setValueAsObject() if you want to do that.
Parameters
[in] index If supplied must be 0 <= index < getNumValues().
Returns
writable reference to the value as an Object
See Also
getValueAsObject(), updValue<T>()
Implements OpenSim::AbstractProperty.
Reimplemented in OpenSim::PropertyObjPtr< T >, OpenSim::PropertyObjPtr< OpenSim::OpenSim::Function >, OpenSim::PropertyObjPtr< OpenSim::Joint >, OpenSim::PropertyObjPtr< OpenSim::Function >, OpenSim::PropertyObjArray< T >, OpenSim::PropertyObjArray< ExternalForce >, OpenSim::PropertyObjArray< Bhargava2004MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< ContactGeometry >, OpenSim::PropertyObjArray< PathPoint >, OpenSim::PropertyObjArray< Umberger2010MuscleMetabolicsProbe_MetabolicMuscleParameter >, OpenSim::PropertyObjArray< Coordinate >, OpenSim::PropertyObjArray< OpenSim::Constraint >, OpenSim::PropertyObjArray< OpenSim::ObjectGroup >, OpenSim::PropertyObjArray< OpenSim::Actuator >, OpenSim::PropertyObjArray< IKTask >, OpenSim::PropertyObjArray< Force >, OpenSim::PropertyObjArray< Joint >, OpenSim::PropertyObjArray< MarkerPair >, OpenSim::PropertyObjArray< DisplayGeometry >, OpenSim::PropertyObjArray< Scale >, OpenSim::PropertyObjArray< OpenSim::Force >, OpenSim::PropertyObjArray< Probe >, OpenSim::PropertyObjArray< OpenSim::Muscle >, OpenSim::PropertyObjArray< Controller >, OpenSim::PropertyObjArray< ModelComponent >, OpenSim::PropertyObjArray< Function >, OpenSim::PropertyObjArray< TrackingTask >, OpenSim::PropertyObjArray< OpenSim::ControlLinearNode >, OpenSim::PropertyObjArray< Measurement >, OpenSim::PropertyObjArray< BodyScale >, OpenSim::PropertyObjArray< Marker >, OpenSim::PropertyObjArray< Analysis >, OpenSim::PropertyObjArray< OpenSim::MarkerWeight >, OpenSim::PropertyObjArray< Body >, OpenSim::PropertyObjArray< Constraint >, OpenSim::PropertyObjArray< Control >, and OpenSim::PropertyObj.
virtual void OpenSim::Property_Deprecated::writeToXMLElement (SimTK::Xml::Element & propertyElement) const inline override virtual
Output a serialized representation of this property by writing its value to the given XML property element.
If the "use default value" attribute is set for this property (meaning we don't have a meaningful value for it) then you should not call this method unless you are trying to serialize the defaults. Note that this method unconditionally serializes the property; it does not check to see whether it should.
This method is not called for the special case of a one-object property, in which case only the object is written to the XML file (without the property element). In all other cases (simple property or property containing an array of objects), the format is
<propertyName> value(s) </propertyName>
and that is the only format produced here since the empty-valued property element is supplied (with the property name as its tag).
Implements OpenSim::AbstractProperty.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & aOut, const Property_Deprecated & aProperty) friend
The documentation for this class was generated from the following file:
C:/ReleaseEnv/src/OpenSim32Branch/OpenSim/Common/Property_Deprecated.h